version: "3.9"

services:

  web:
    image: kanap
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend