version: "3.9"

services:

  backend:
    image: kanap
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend

  frontend:
    image: kanap
    build: .
    ports: 
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
